security:
    # Configuration des encoders de mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Configuration des providers d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuration des firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: form_login

            custom_authenticator: App\Security\UserAuthenticator

            form_login:
                login_path: app_login
                check_path: app_login
                success_handler: App\Security\LoginSuccessHandler

            logout:
                path: app_logout
                target: /login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    # Contrôle des accès
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/agent-bancaire, roles: ROLE_AGENT_BANCAIRE }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/dashboard, roles: ROLE_USER }
